  - name: Save .state cache
    if: always()
    continue-on-error: true   # ← evita que un fallo de cache marque el job como failed
    uses: actions/cache/save@v4
    with:
      path: .state
      key: agrobot-state-${{ steps.date.outputs.today }}
