name: Postear precios agro

on:
  schedule:
    - cron: "0 15 * * 1-5"   # 12:00 ART lun-vie (15:00 UTC)
    - cron: "0 21 * * 1-5"   # 18:00 ART lun-vie (21:00 UTC)
    - cron: "0 23 * * 0"     # 20:00 ART domingos (23:00 UTC) - Resumen semanal
  workflow_dispatch:          # correrlo manualmente cuando quieras

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      # --- Cache para mantener el estado entre mediodía y cierre ---
      - name: Get UTC date (YYYY-MM-DD)
        id: date
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Restore .state cache (same day)
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: .state
          key: agrobot-state-${{ steps.date.outputs.today }}

      # --- Ejecutar bot ---
      - name: Run bot
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          UREA_USD_T: ${{ secrets.UREA_USD_T }}
          INSUMOS_CSV_URL: ${{ secrets.INSUMOS_CSV_URL }}
        run: |
          mkdir -p .state
          python bot.py

      # --- Guardar .state para el próximo run del día ---
      - name: Save .state cache
        if: always()
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: .state
          key: agrobot-state-${{ steps.date.outputs.today }}

