name: Test resumen semanal (simple)

on:
  workflow_dispatch:  # lo ejecutás manualmente desde Actions

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run bot (SEMANA)
        env:
          X_API_KEY: ${{ secrets.X_API_KEY }}
          X_API_SECRET: ${{ secrets.X_API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
          UREA_USD_T: ${{ secrets.UREA_USD_T }}
          INSUMOS_CSV_URL: ${{ secrets.INSUMOS_CSV_URL }}
          RUN_MODE: SEMANA
        run: python bot.py
